CC = gcc

TubeCountingFiles = $(wildcard Source/Tubes/*.c) $(wildcard Source/Counting/*.c) Source/Utilities/Utilities.c
ArenaFiles= $(wildcard Source/MemoryArena/**/*.c) 
TestFiles = $(wildcard Tests/*.c) $(wildcard Tests/**/*.c) $(wildcard Tests/**/**/*.c) 

main: $(TubeCountingFiles) $(ArenaFiles) 
	$(CC) Source/main.c $(TubeCountingFiles) $(ArenaFiles)  -Wall -pedantic -o .build/TubeCounting.exe

debug: $(TubeCountingFiles) $(ArenaFiles) 
	$(CC) Source/main.c $(TubeCountingFiles) $(ArenaFiles)  -g -Wall -pedantic -o .build/TubeCounting.exe

Tests: $(TubeCountingFiles) $(ArenaFiles) $(TestFiles)
	$(CC) $(TestFiles) $(TubeCountingFiles) $(ArenaFiles)  -g -Wall -pedantic -o .build/Tests.exe


