CC = gcc
GenFiles = ../Utilities/Utilities.c
ArenaFiles= $(wildcard ArenaBase/*.c) $(wildcard ArenaArray/*.c) 
TestFiles = $(wildcard Tests/*.c) $(wildcard Tests/ArenaBase/*.c) $(wildcard Tests/ArenaArray/*.c)

Test: $(ArenaFiles) $(TestFiles) $(GenFiles)
	$(CC) $(ArenaFiles) $(TestFiles) $(GenFiles) -Wall -pedantic -o output.exe

ArenaMin: $(ArenaFiles) $(GenFiles)
	$(CC) $(ArenaFiles) $(GenFiles) -Wall -pedantic -o output.exe